/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp poi_contentaccessmodule.xml -p com.poiservice.POIContentAccessModule -a POIContentAccessModule_adapter
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "POIContentAccessModule_adapter.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class POIContentAccessModuleAdaptor
 */

POIContentAccessModuleAdaptor::POIContentAccessModuleAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

POIContentAccessModuleAdaptor::~POIContentAccessModuleAdaptor()
{
    // destructor
}

void POIContentAccessModuleAdaptor::addPOI(uint category_id, double poi_Lat, double poi_Lon)
{
    // handle method call com.poiservice.POIContentAccessModule.addPOI
    QMetaObject::invokeMethod(parent(), "addPOI", Q_ARG(uint, category_id), Q_ARG(double, poi_Lat), Q_ARG(double, poi_Lon));
}

void POIContentAccessModuleAdaptor::removePOIs(uint category_id)
{
    // handle method call com.poiservice.POIContentAccessModule.removePOIs
    QMetaObject::invokeMethod(parent(), "removePOIs", Q_ARG(uint, category_id));
}

