/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp poi_contentaccessmodule.xml -p com.poiservice.POIContentAccessModule -a POIContentAccessModule_adapter
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef POICONTENTACCESSMODULE_ADAPTER_H
#define POICONTENTACCESSMODULE_ADAPTER_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.poiservice.POIContentAccessModule
 */
class POIContentAccessModuleAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.poiservice.POIContentAccessModule")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.poiservice.POIContentAccessModule\">\n"
"    <method name=\"addPOI\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"category_id\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"poi_Lat\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"poi_Lon\"/>\n"
"    </method>\n"
"    <method name=\"removePOIs\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"category_id\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    POIContentAccessModuleAdaptor(QObject *parent);
    virtual ~POIContentAccessModuleAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void addPOI(uint category_id, double poi_Lat, double poi_Lon);
    void removePOIs(uint category_id);
Q_SIGNALS: // SIGNALS
};

#endif
